name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Read Readme
        id: read
        uses: juliangruber/read-file-action@v1
        with:
          path: ./README.md
      - name: output the message on actions result
        uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: ${{ steps.read.outputs.content }}
      - run: ls -l # Liste les fichier du répertoire courant
      - run: cat README.md | cowsay # Affiche le contenu du fichier `README.md` à la base du dépôt